### ISSUE TITLE
My projects should be instance specific

### ISSUE THREAD

**Issue by harlantwood** [CoMakery/swarmbot#4]
- [x] Title should be: [slack instance image] [slack instance name] Projects **on app home page**
- [x] Title should be: [slack instance image] [slack instance name] Projects **on projects index page**
- [x] test with slack team that has no team image

_From @aquabu on February 29, 2016 22:59_

This should be the site wide behavior.

see also: https://projects.invisionapp.com/d/main#/console/6341574/137676916/preview

_Copied from original issue: citizencode/swarmbot#424_

**Comment by harlantwood** [comment]
_From @aquabu on March 1, 2016 18:12_

https://projects.invisionapp.com/d/main#/console/6341574/137676916/preview
Title should be:
[slack instance image] [slack instance name] Projects

**Comment by harlantwood** [comment]
@aquabu this looks good on app home and projects index; please check that all is accomplished for "site wide behavior" as well.

**Comment by aquabu** [comment]
@harlantwood yes that works. I'm noticing some stuff about capitalization and search results that I'll put in another story.
