### ISSUE TITLE
improve our zenhub experience

### ISSUE THREAD

**Issue by harlantwood** [CoMakery/swarmbot#40]
we wish we could have default points (2), and a current default milestone

- [x] look for zenhub project settings, if exists
- [x] find keyboard shortcuts for points and milestones
- [x] request features from zenhub: default points, default milestone

**Comment by aquabu** [comment]
Sent to support


I'm using Zenhub and I am enjoying it. Here are a few features that would speed up my workflow:
- Entering estimates for the burndown takes a lot of time and unestimated stories don't show up. I like to have a default story size (e.g. 2). Would it be possible to auto estimate or to give unestimated stories a default size in the burndown chart of 2?
- It takes a lot of clicks to get issues into the burndown chart. One solution would be to automatically enter issues for a milestone (for the burndown chart)
- The month numbering on the burndown chart is day/month. That's the reverse of my US brain. Could you use month/day or MONTH_ABREVIATION DAY?

**Comment by aquabu** [comment]
When viewing an issue:
- "e" brings up the estimate dialog (zenhub shortcut)
- "m" brings up the milestone dialog (github shortcut)
